### ISSUE TITLE
Calendar fails to show previous weeks when there is no valid current week

### ISSUE THREAD

**Issue by EnderShadow** [karlstolley/wd#4]
This is likely due to the html not containing an element with the id "this-week" on line 153 of the javascript file.

**Comment by karlstolley** [comment]
Thanks @EnderShadow -- it was actually something I'd put off including in the upstream HTML template I use to generate the site. Fix is posted and you can see it here: https://github.com/karlstolley/jekyll-theme-open-course/commit/9d4d746a66d298bdd4c950ff18af68860929eda7
